### ISSUE TITLE
Support strict-api for generated classes

### ISSUE THREAD

**Issue by pascaldornfeld** [gaelmarhic/Quadrant#11]
In my architecture I got a common module and multiple ui modules. I apply the plugin on the common module so the generated classes are available in all ui modules. In my common module I use strict api so I don't accidentally expose code to lower modules (freeCompilerArgs = ["-Xexplicit-api=strict"]). Because of that I get exceptions from the generated classes: "Visibility must be specified in explicit API mode".
It can be fixed by adding "public" in front of every object and constant.

**Comment by gaelmarhic** [comment]
Done in #12.

**Comment by gaelmarhic** [comment]
Hey there @pascaldornfeld.

First of all, thank you for your interest in `Quadrant` and for reporting this issue.

I have just created a new version with the fix:
https://github.com/gaelmarhic/Quadrant/releases/tag/v1.7
https://plugins.gradle.org/plugin/com.gaelmarhic.quadrant

Could you test it on your project and let me know how it goes?

Thanks.

**Comment by pascaldornfeld** [comment]
I tested it in my app. It compiles and app works.
![image](https://user-images.githubusercontent.com/52472959/149635743-8f58993f-6182-48f2-a525-82427ce664b3.png)

For comparision, this was 1.6.1:
![image](https://user-images.githubusercontent.com/52472959/149635884-c4fdef22-0e65-46bc-931e-04d93a2eb750.png)
