### ISSUE TITLE
Support BroadcastReceivers and Services

### ISSUE THREAD

**Issue by nikclayton** [gaelmarhic/Quadrant#14]
Hi -- first, thanks for writing this plugin, very handy.

Second, have you considered also creating constants for other manifest elements; specifically `BroadcastReceiver` and `Service`? They're also addressed using intents, and have the same dependency cycle issues in a modular codebase.

**Comment by gaelmarhic** [comment]
Hey Nik,
Thanks a lot for reaching out!
I had not thought of extending the plugin to BroadcastReceiver and Service. That is a good idea actually!
Unfortunately, I don't have the capacity to implement it at the moment.
Feel free to make a PR if you need those features and I will review it!
Kind regards.
Gaël

**Comment by nikclayton** [comment]
OK, I'll put that on my January todo list

**Comment by gaelmarhic** [comment]
Sounds good. Closing the issue for now.
Cheers!
