### ISSUE TITLE
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.vikash.mycomposelearningapp/com.viksa.weatherapp.HomeActivity}; have you declared this activity in your AndroidManifest.xml?

### ISSUE THREAD

**Issue by VIkash2601** [gaelmarhic/Quadrant#18]
```
public object QuadrantConstants {
  public const val KOTLIN_D_S_L_ACTIVITY: String =
      "com.vikash.mycomposelearningapp.kotlindsl.KotlinDSLActivity"

  public const val NAVIGATION_ACTIVITY: String =
      "com.vikash.mycomposelearningapp.navexample.NavigationActivity"

  public const val LOGIN_ACTIVITY: String = "com.vikash.mycomposelearningapp.LoginActivity"

  public const val MAIN_ACTIVITY: String = "com.vikash.mycomposelearningapp.MainActivity"

  public const val HOME_ACTIVITY: String = "com.viksa.weatherapp.HomeActivity"
}
```

But I am getting `android.content.ActivityNotFoundException: Unable to find explicit activity class {com.vikash.mycomposelearningapp/com.viksa.weatherapp.HomeActivity}; have you declared this activity in your AndroidManifest.xml?`

**Comment by gaelmarhic** [comment]
Hi @VIkash2601,
Thanks for reaching out.
Could you, please, provide me with a sample project with the issue, so that I can reproduce it and try to understand what the problem is?
Thanks!

**Comment by VIkash2601** [comment]
Hey @gaelmarhic Sorry for the late reply, I just resolved the issue. Closing it as no further assistance is required. Thanks for your time.

**Comment by gaelmarhic** [comment]
Hey @VIkash2601.
Glad you could solve it!
Kind regards.
