### ISSUE TITLE
Activity name misssing after generated

### ISSUE THREAD

**Issue by anwarpro** [gaelmarhic/Quadrant#9]
In version 1.6, When activity names are not declared in a sequence, the first group of activity names missing from the generated class.

`
<activity name="com.example.A"/>
<receiver name="..."/>
<activity name="com.example.B"/>
`

in this situation, A is missing.

**Comment by gaelmarhic** [comment]
Hey there @anwarpro!

First of all, thank you for your interest in `Quadrant` as well as for reporting this bug.

Thanks to your explanation, I was able to reproduce it. 

I have already merged the fix (#10) to `master` and published a new version:
https://github.com/gaelmarhic/Quadrant/releases/tag/v1.6.1
https://plugins.gradle.org/plugin/com.gaelmarhic.quadrant

Could you test it on your project and see if it works as expected?

Thanks again,

Gaël
